// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/image_service.proto

package images

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_proto_image_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_proto_image_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ThumbnailShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          string                 `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailShort) Reset() {
	*x = ThumbnailShort{}
	mi := &file_proto_image_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailShort) ProtoMessage() {}

func (x *ThumbnailShort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailShort.ProtoReflect.Descriptor instead.
func (*ThumbnailShort) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{2}
}

func (x *ThumbnailShort) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ThumbnailShort) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ThumbnailShort) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	CompressedUrl *string                `protobuf:"bytes,3,opt,name=compressed_url,json=compressedUrl,proto3,oneof" json:"compressed_url,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Mime          string                 `protobuf:"bytes,6,opt,name=mime,proto3" json:"mime,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	Thumbnails    []*ThumbnailShort      `protobuf:"bytes,8,rep,name=thumbnails,proto3" json:"thumbnails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageResponse) Reset() {
	*x = ImageResponse{}
	mi := &file_proto_image_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResponse) ProtoMessage() {}

func (x *ImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResponse.ProtoReflect.Descriptor instead.
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{3}
}

func (x *ImageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ImageResponse) GetCompressedUrl() string {
	if x != nil && x.CompressedUrl != nil {
		return *x.CompressedUrl
	}
	return ""
}

func (x *ImageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ImageResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageResponse) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ImageResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *ImageResponse) GetThumbnails() []*ThumbnailShort {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

var File_proto_image_service_proto protoreflect.FileDescriptor

const file_proto_image_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/image_service.proto\x12\x06images\"(\n" +
	"\x12UploadImageRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"!\n" +
	"\x0fGetImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x0eThumbnailShort\x12\x12\n" +
	"\x04size\x18\x01 \x01(\tR\x04size\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xb5\x02\n" +
	"\rImageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12*\n" +
	"\x0ecompressed_url\x18\x03 \x01(\tH\x00R\rcompressedUrl\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mime\x18\x06 \x01(\tR\x04mime\x12(\n" +
	"\rerror_message\x18\a \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x126\n" +
	"\n" +
	"thumbnails\x18\b \x03(\v2\x16.images.ThumbnailShortR\n" +
	"thumbnailsB\x11\n" +
	"\x0f_compressed_urlB\x10\n" +
	"\x0e_error_message2\x90\x01\n" +
	"\fImageService\x12B\n" +
	"\vUploadImage\x12\x1a.images.UploadImageRequest\x1a\x15.images.ImageResponse\"\x00\x12<\n" +
	"\bGetImage\x12\x17.images.GetImageRequest\x1a\x15.images.ImageResponse\"\x00B$Z\"./internal/delivery/grpc/pb;imagesb\x06proto3"

var (
	file_proto_image_service_proto_rawDescOnce sync.Once
	file_proto_image_service_proto_rawDescData []byte
)

func file_proto_image_service_proto_rawDescGZIP() []byte {
	file_proto_image_service_proto_rawDescOnce.Do(func() {
		file_proto_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_image_service_proto_rawDesc), len(file_proto_image_service_proto_rawDesc)))
	})
	return file_proto_image_service_proto_rawDescData
}

var file_proto_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_image_service_proto_goTypes = []any{
	(*UploadImageRequest)(nil), // 0: images.UploadImageRequest
	(*GetImageRequest)(nil),    // 1: images.GetImageRequest
	(*ThumbnailShort)(nil),     // 2: images.ThumbnailShort
	(*ImageResponse)(nil),      // 3: images.ImageResponse
}
var file_proto_image_service_proto_depIdxs = []int32{
	2, // 0: images.ImageResponse.thumbnails:type_name -> images.ThumbnailShort
	0, // 1: images.ImageService.UploadImage:input_type -> images.UploadImageRequest
	1, // 2: images.ImageService.GetImage:input_type -> images.GetImageRequest
	3, // 3: images.ImageService.UploadImage:output_type -> images.ImageResponse
	3, // 4: images.ImageService.GetImage:output_type -> images.ImageResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_image_service_proto_init() }
func file_proto_image_service_proto_init() {
	if File_proto_image_service_proto != nil {
		return
	}
	file_proto_image_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_image_service_proto_rawDesc), len(file_proto_image_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_image_service_proto_goTypes,
		DependencyIndexes: file_proto_image_service_proto_depIdxs,
		MessageInfos:      file_proto_image_service_proto_msgTypes,
	}.Build()
	File_proto_image_service_proto = out.File
	file_proto_image_service_proto_goTypes = nil
	file_proto_image_service_proto_depIdxs = nil
}
